version: '3'

services:
  go:
    build: .
    env_file:
      - .env
    ports:
      - '5000:5000'
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lis
    ports:
      - '5432:5432'
