-- +goose Up

CREATE TABLE materials (
    id UUID PRIMARY KEY,
    title VARCHAR(255) UNIQUE NOT NULL,
    file_url VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- +goose Down

DROP TABLE materials;